### PR TITLE
Use custom icon for diagnostics section

### LINKED ISSUE #14: Settings icon is the default cog icon
Going to the settings view, in the left sidebar we can see:

screen shot 2017-08-03 at 14 33 52

It should be the same or similar to the icon in the apps view:

screen shot 2017-08-03 at 14 36 05

cc @felixheidecke

### PR DESCRIPTION
**Pull request by tomneedham**
Fixes #14 .

But needs a new svg with the colours fixed so that it is grey, not white on white background. 

Hacky fix, but gets it done until we update the settings interface

@felixheidecke can you sort the icon?

### CODE REVIEW

**Comment by mrow4a** [comment]
Hmm, does not display the icon for me ;/

**Comment by mrow4a** [comment]
Ohh, sorry, just read that it is because of background

**Comment by mrow4a** [comment]
Pushed amend on commit, now will work. @tomneedham check it out

**Comment by tomneedham** [comment]
👍

**Pull request merged**
